### ISSUE TITLE
Unable to destroy activity 

### ISSUE THREAD

**Issue by giovannyreyeso** [ivan200/PhotoBarcode#2]
Hi, i am getting this error afeter back to activity ( on backpressed or read the barcode ) i am using the example in README.  any idea?

`    java.lang.RuntimeException: Unable to destroy activity {com.reyes.refreyes/com.ivan200.photobarcodelib.PhotoBarcodeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
`

` Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
        at com.ivan200.photobarcodelib.CameraSource$FrameProcessingRunnable.release(CameraSource.java:1257)
        at com.ivan200.photobarcodelib.CameraSource.release(CameraSource.java:323)
        at com.ivan200.photobarcodelib.CameraSourcePreview.release(CameraSourcePreview.java:144)
        at com.ivan200.photobarcodelib.PhotoBarcodeActivity.clean(PhotoBarcodeActivity.java:927)
        at com.ivan200.photobarcodelib.PhotoBarcodeActivity.onDestroy(PhotoBarcodeActivity.java:914)
        at android.app.Activity.performDestroy(Activity.java:7241)`

**Comment by ivan200** [comment]
Hi.
Do you need a QR scanner or photo taking?

If qr, then what is your minsdk?
if 21+, then i recommend you to use CameraX + MlKit
like here
https://github.com/ivan200/EasyScanner
i wrote this example for myself, but I haven't published it yet (I did it a couple of minutes ago).

There is
- good camera support
- no need Google Play Services anymore
- great customization (you can also configure recognition of aztec or pdf417 codes)
- easy implementation (just about 2 classes for base functionality)
- focus on touch
- zoom

if you need photo taking, then i have good library PhotoAdapter
It was written on top of `natario1/CameraView`
And i think i need to rewrite it with using CameraX, and also update targetsdk for newer versions

**Comment by giovannyreyeso** [comment]
Thank u! @ivan200 i will check your project EasyScanner, because my project is min sdk > 21
