### ISSUE TITLE
App Crashes after scanning barcode

### ISSUE THREAD

**Issue by dinukapj** [ivan200/PhotoBarcode#3]
The library retrieves the barcode number but immediately crashes with this error:

```
java.lang.RuntimeException: Unable to destroy activity {com.test.testapp/com.ivan200.photobarcodelib.PhotoBarcodeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5390)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5423)
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
        at com.ivan200.photobarcodelib.CameraSource$FrameProcessingRunnable.release(CameraSource.java:1257)
        at com.ivan200.photobarcodelib.CameraSource.release(CameraSource.java:323)
        at com.ivan200.photobarcodelib.CameraSourcePreview.release(CameraSourcePreview.java:144)
        at com.ivan200.photobarcodelib.PhotoBarcodeActivity.clean(PhotoBarcodeActivity.java:927)
        at com.ivan200.photobarcodelib.PhotoBarcodeActivity.onDestroy(PhotoBarcodeActivity.java:914)
        at android.app.Activity.performDestroy(Activity.java:8316)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5377)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5423) 
        at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47) 
        at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
```

**Comment by ivan200** [comment]
sorry, but this lib is deprecated and not maintainable
you can try to implement barcode scanning like this
https://github.com/ivan200/EasyScanner/blob/master/app/src/main/java/com/ivan200/easyscanner/MainActivity.kt

this is example of using camerax + mlkit for scanning barcodes

just copy couple classes what your need
